### ISSUE TITLE
Updates to the contact page

### ISSUE THREAD

**Issue by Abhi-Raj** [photobox/pbx-group-security#102]
contacts page need to link to our social media presence
- gs linkedin and twitter
https://twitter.com/pbg_security
https://www.linkedin.com/groups/12079174

- personal twitter accounts (for the ones that are happy to publish it)
Dinis Cruz - https://twitter.com/DinisCruz
Abhi Raj - https://twitter.com/_Abhiraj_
@JemmaDSmith - Twitter to be updated

**Comment by fzipi** [comment]
Contact page updated.

**Comment by DinisCruz** [comment]
Hi @JemmaDSmith what twitter handle do you want to use?

**Comment by JemmaDSmith** [comment]
@DinisCruz I don't have one that suits this audience, my professional one is @jemarketinguk but this relates to marketing content. Let me know if you need me to create a new one
