### ISSUE TITLE
Add link to edit an page at the bottom of the page

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#103]
this makes it easier to edit content when just using the web (and github)

**Comment by fzipi** [comment]
Created PR #105 for this.

![screenshot from 2017-12-16 13-57-39](https://user-images.githubusercontent.com/3012076/34072623-4d191a90-e269-11e7-809d-04ee64ccb1e3.png)

Tried to keep the look and feel from the site.
