### ISSUE TITLE
Remove labels that are not relevant

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#104]
for example these

![image](https://user-images.githubusercontent.com/656739/34072216-23276536-e27b-11e7-8c1d-1e192f13fe59.png)

**Comment by fzipi** [comment]
Removed the A* labels.

**Comment by DinisCruz** [comment]
done 
![image](https://user-images.githubusercontent.com/656739/34080770-211f89ce-e33b-11e7-9174-ac45435c8ecb.png)
