### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#110]
The fix for #95 broke the search

![image](https://user-images.githubusercontent.com/656739/34080745-daab7048-e33a-11e7-89db-6ff1a0faa1ef.png)

**Comment by fzipi** [comment]
@DinisCruz For the dev site I usually end having two configs. For example, having a `config-dev.toml` with `baseURL: dev-...`, and keep `config.toml` for production. Then in your dev webhook you end running `hugo --config config-dev.toml`. Also in dev is normal to have an empty GA code in the same config.

**Comment by DinisCruz** [comment]
yeah that makes sense. I'll try to update the CI server script (which is running inside docker)

**Comment by fzipi** [comment]
Now, when merging PR #117, we have the full baseURL again in our config. I think we can enable the search again, so that is what i will try.

**Comment by fzipi** [comment]
Search is working again. I uncommented the partial in sidebar.html (d236612).

Search can be disabled in the `config.toml` setting:
```
# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true # <=== change to false
```
