### ISSUE TITLE
Refactor roles table using partials

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#116]
So that this code is not duplicated

![image](https://user-images.githubusercontent.com/656739/34085580-ea74e446-e38a-11e7-951a-57cb6b0f4b1b.png)

here is what the page looks like (with both sets of tables)

![image](https://user-images.githubusercontent.com/656739/34085589-0b575310-e38b-11e7-92d5-19e408d1e57e.png)

**Comment by fzipi** [comment]
Added 0205309 for this. It bothers me that both `contractor type` aren't aligned... I'll see this tomorrow.

**Comment by JemmaDSmith** [comment]
@fzipi can we close issue?

**Comment by fzipi** [comment]
Yes!
