### ISSUE TITLE
Site CSS is broken

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#119]
![image](https://user-images.githubusercontent.com/656739/34099793-70e39822-e3d8-11e7-9882-aeab37508d70.png)

**Comment by DinisCruz** [comment]
fixed with https://github.com/photobox/pbx-group-security/commit/bb83ed11e03264eaf697fa23049652a6b9bc3eac

**Comment by fzipi** [comment]
@DinisCruz I changed both the `config.toml` *and* the URLs, because locally it was making two additional requests (the first was a redirect from //all.js to /all.js), so I take out the extra '/'. Going live it was lacking that one.
