### ISSUE TITLE
remove image that is taking 50% of page load size 

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#122]
And doesn't seem that is being used

![image](https://user-images.githubusercontent.com/656739/34111573-086b0418-e402-11e7-8453-dc6dabd0f76e.png)

https://pbx-group-security.com/img/photogrid.jpg (it's 436k)

**Comment by fzipi** [comment]
@DinisCruz The photogrid is being used. Is the background in the carousel. Maybe we can resize or compress it.

**Comment by JemmaDSmith** [comment]
@fzipi can you replace with pbx-group-security/static/img/Photoboxgroup_carouselimgRGB.png

**Comment by fzipi** [comment]
Replaced in b3a092e.
