### ISSUE TITLE
Add social buttons to website

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#45]
Namely Twitter, Facebook, LInkedIn and others

**Comment by fzipi** [comment]
The icons in the default theme are in the topbar. You just need to enable it.

![screenshot-2017-12-12 photobox group security](https://user-images.githubusercontent.com/3012076/33866373-1e9e2e68-ded5-11e7-83c3-9bd99759c751.png)

Related to #63.

**Comment by JemmaDSmith** [comment]
How do we enable?

**Comment by fzipi** [comment]
Easy: in file `config.toml`, around line 105,

```
# Enable or disable top bar with social icons
[params.topbar]
    enable = true # <===== change this from false to true
```

**Comment by JemmaDSmith** [comment]
Actioned
