### ISSUE TITLE
Add threads and comments feature to site

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#46]
For example https://disqus.com/?

Are there alternatives?

**Comment by fzipi** [comment]
I like https://staticman.net/, which gives you on PR for each comment on your site. Is like having the same flow but for comments. For hugo is here: https://github.com/eduardoboucas/hugo-plus-staticman.

**Comment by fzipi** [comment]
If you want to use disqus, just add `disqusShortname` to config.toml, at the same level of googleAnalytics.

```
# Enable comments by entering your Disqus shortname
disqusShortname = "<whatever the shortname is>"
```

**Comment by fzipi** [comment]
We settled on using disqus.
