### ISSUE TITLE
Add amber support to website CI

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#50]
To make the HTML editing process much easier

https://github.com/eknkc/amber

**Comment by fzipi** [comment]
There is no need to setup anything, as amber templates are supported by hugo without additional magic.

For each  amber template, it will be compiled to html and included.

One thing that you have now is that your base templates are hugo templates, and if want to convert it will take some time...

**Comment by fzipi** [comment]
Furthermore, in this case that we already have templates available, can be difficult to change to amber.

**Comment by fzipi** [comment]
I think this can be closed.
