### ISSUE TITLE
Import labels from Owasp Maturity Models project to this repo

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#54]
Since they provide a really nice way to label issues and to assign priorites

see https://github.com/owasp/maturity-models/labels

for example the P0 to P3 ones

![image](https://user-images.githubusercontent.com/656739/33795260-fa0ec018-dcd5-11e7-987c-59c33998caf5.png)

**Comment by Abhi-Raj** [comment]
Closed. https://github.com/photobox/pbx-group-security/labels
