### ISSUE TITLE
Remove all CDN dependencies and make all resources load locally

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#59]
Not only this will have security advantages (not loading resources from 3rd party domains) it will allow offline development

**Comment by DinisCruz** [comment]
here are some examples of what happens when we run the site offline

![image](https://user-images.githubusercontent.com/656739/33936529-ca9cb284-dff7-11e7-9859-0e47cbc59520.png)

![image](https://user-images.githubusercontent.com/656739/33936542-d2f6eab2-dff7-11e7-8c2b-fe0db4985ba4.png)

**Comment by fzipi** [comment]
Referenced PR solved this one.
