### ISSUE TITLE
Update social icons

### ISSUE THREAD

**Issue by Abhi-Raj** [photobox/pbx-group-security#63]
Update social icons Photoboxgroup_mailLogo50pxRGB.png, Photoboxgroup_githubLogo50pxRGB.png, Photoboxgroup_twitterLogo50pxRGB.png

**Comment by fzipi** [comment]
@Abhi-Raj Are this icons going into the topbar? In that case, we need to adapt the top bar size. See example below:
![social example](https://user-images.githubusercontent.com/3012076/33856544-398521c4-dea7-11e7-9afb-eb95a4709e49.png)

**Comment by DinisCruz** [comment]
this is not relevant any more since we don't have the top bar
