### ISSUE TITLE
Remove the requirement for images in testimonials

### ISSUE THREAD

**Issue by Abhi-Raj** [photobox/pbx-group-security#64]
Remove the requirement for images in testimonials - in chrome, this is not shown, on safari, I see a broken image icon

**Comment by fzipi** [comment]
@Abhi-Raj I've fixed this one. But you need *first* to upload 3 images for each avatar:

- `static/img/testimonials/person-1.jpg` will be Jemma
- `static/img/testimonials/person-2.jpg` will be You
- `static/img/testimonials/person-3.jpg` will be Ann-Marie

Then you can merge PR #73 to solve this one.

**Comment by fzipi** [comment]
As @DinisCruz merged the previous PR (#73 ) and merged it, I made a new PR (#74) using pictures from github & web. I'm sure that those pictures can be replaced with some others with more quality...

**Comment by fzipi** [comment]
There are no more images in testimonials per #80 , so we can close this one.
