### ISSUE TITLE
Images are too big (in Hugo)

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#70]
We need a solution to control the size of images 

for example in https://pbx-group-security.com/challenges/soc-engineer/

![image](https://user-images.githubusercontent.com/656739/33842311-13600a32-de92-11e7-8f0a-44303e35b947.png)

**Comment by fzipi** [comment]
I've added a `<figure>` shortcode to fix the size in PR #86. Can add a `class` to that shortcode also, but maybe these particular images won't be seen good in responsive class.

**Comment by DinisCruz** [comment]
this is fixed

@Abhi-Raj can you keep an eye on issues like this to make sure they are closed when done
