### ISSUE TITLE
Ordering the site images

### ISSUE THREAD

**Issue by fzipi** [photobox/pbx-group-security#79]
It will be good if we can have subdirectories for images, so it's easier afterwards to know where to save each file.

I propose to use one directory per "content type", for example:

- Save blog banner images in '/img/blog'
- Save challenges images in '/img/challenge'
...
And so on.

It will be easy for others also after creating content to follow this simple rules to know where to put each file, and why.

I can write a CONTRIBUTING.md file for this repo if needed...

**Comment by JemmaDSmith** [comment]
Please go ahead

**Comment by fzipi** [comment]
I've created PR #83 for this. Please let me know if it works for you.

Now I will do the actual reordering.

**Comment by fzipi** [comment]
PR #84 does the actual reordering of files and images in front matter.

**Comment by fzipi** [comment]
As both PRs were merged, I think we can close this one. 

One of the nice things of having a contributing file is that github will show the text `Before you submit a pull request please review the contributing guidelines for this repository. ` with a link to the contributing file.
