### ISSUE TITLE
Team Title in Testimonials needs some work

### ISSUE THREAD

**Issue by Abhi-Raj** [photobox/pbx-group-security#80]
![image](https://user-images.githubusercontent.com/33575821/33867891-85cfd4ea-decd-11e7-8c4d-f0e47b5f6f69.png)
Highlighted items need some work

**Comment by JemmaDSmith** [comment]
Vote of 2 is that we remove images so that the text flows better

**Comment by fzipi** [comment]
You can always resume text to flow better. But if you want I can make images not be shown at all.

**Comment by JemmaDSmith** [comment]
Yes please

**Comment by fzipi** [comment]
I've committe efb797e to hide images in testimonials. The text "Group Security Operations Manager" is wider than the space assigned so it continues on the next level.  Should we increase the box width or decrease the text length?

**Comment by Abhi-Raj** [comment]
@fzipi - was any modification done on (increasing the box width / decrease the text length)? I believe the longest title would be that of Jemma which now is looking good without an image. Hopefully, we should not get into trouble anytime soon

**Comment by fzipi** [comment]
No, not modified at all. If it's good for you, it's good for me.
