### ISSUE TITLE
remove top banner from site

### ISSUE THREAD

**Issue by DinisCruz** [photobox/pbx-group-security#87]
Since some of the links are broken and it is not shown on all pages

![image](https://user-images.githubusercontent.com/656739/33937283-c47a7cf8-dffa-11e7-83d4-e7e090a7c068.png)

the links to github should be on the Dev pages and the links to social media can be added to the bottom or to the contacts page

**Comment by fzipi** [comment]
@DinisCruz To hide the top bar, just use this setting in `config.toml`:
```
# Enable or disable top bar with social icons
[params.topbar]
    enable = true # <======= set this to false.
```

The social icons can be placed at the bottom.

**Comment by DinisCruz** [comment]
ok, just changed it so that the top banner doesn't show anymore

![image](https://user-images.githubusercontent.com/656739/34069917-1ee28916-e252-11e7-8d54-d2237ce643ee.png)

**Comment by DinisCruz** [comment]
this is what it looks like now
![image](https://user-images.githubusercontent.com/656739/34069925-3298ce48-e252-11e7-89d4-2e1093c266d0.png)
