### ISSUE TITLE
Image *thumbnails and image within the blog* needs to follow a sizing standard

### ISSUE THREAD

**Issue by Abhi-Raj** [photobox/pbx-group-security#92]
![image](https://user-images.githubusercontent.com/33575821/33956774-a08355f0-e00d-11e7-8af2-d42cbae66437.png)

a. Currently, thumbnails of the blog (https://pbx-group-security.com/blog/) have different shape and size. Needs to be consistent on the website.

b. Image size within each blog is different and doesn't look standardized. Needs some tuning and should be symmetrical in nature. <example a: https://pbx-group-security.com/blog/, example b: https://pbx-group-security.com/blog/2017/12/11/we-need-your-help/)

**Comment by fzipi** [comment]
The a) case is the blog listing. All images are trated as responsive, but the chosen image is too small and can't be upsized without losing quality. Therefore I changed that one for the same as the post above. If there is no image to supply for the banner of a blog entry, it will use the 400x400 placeholder.

In the b) case, the template for the blog page is showing the banner. But the original does not have this feature, e.g. [this post](https://themes.gohugo.io/theme/hugo-universal-theme/blog/2015/10/02/linked-post/). So I deleted the image from the single blog post view.

I think that we need to have a visual attraction on each blog post, we can have two pictures: one for the listing and another for the blog post. We can name them 'banner-list' and 'banner' respectively, and have quality images for each presentation.

I'm pushing this changes in PR #93.
